[10:25:18:460] [WARN] - com.alibaba.dubbo.remoting.transport.AbstractClient$1.run(AbstractClient.java:160) -  [DUBBO] client reconnect to 192.168.20.2:20880 find error . url: dubbo://192.168.20.2:20880/com.xiniunet.security.service.SecurityService?anyhost=true&application=web_tutorial&check=false&codec=dubbo&dubbo=2.5.3&heartbeat=60000&interface=com.xiniunet.security.service.SecurityService&loadbalance=roundrobin&methods=checkValification,modifyMemberLoginPassword,resetUserLoginPassword,verifyTransactionPassword,createPassport,deleteOauth,getApplicationAllListByTenantId,createUserOauth,getVersion,createLoginPassword,createTenantUserLoginPassword,checkLoginCode,findUserOauth,createVerificationCode,createLoginCode,searchUserHasSetTransactionPassword,login,createValification,findApplicationInstall,issuePassportByAppkey,revokePassport,existInstallByAppKey,getUserByAccountAndMobile,resetUserTransactionPassword,updateResetLoginPassword,loginByOauth,changeMobileNumber,modifyLoginPassword,getAuthList,resetPasswordByMobile,isResetableLoginPassword,updateUserApplication,updateUserTransactionPassword,searchUserApplication,initializedApplication,findVerificationCode,updateLoginPasswordByVerifyCode,getApplicationAllListByUserId,getPassport,createBatchLoginPassword&monitor=dubbo%3A%2F%2F192.168.20.2%3A2181%2Fcom.alibaba.dubbo.registry.RegistryService%3Fapplication%3Dweb_tutorial%26dubbo%3D2.5.3%26file%3Ddubbo-register-192.168.20.2-web_tutorial.properties%26owner%3Dall%26pid%3D12416%26protocol%3Dregistry%26refer%3Ddubbo%253D2.5.3%2526interface%253Dcom.alibaba.dubbo.monitor.MonitorService%2526pid%253D12416%2526timestamp%253D1490685013286%26registry%3Dzookeeper%26timestamp%3D1490685013285&owner=all&payload=353554432&pid=12416&retries=0&revision=4.6.1-20170322.072501-1&side=consumer&timeout=60000&timestamp=1490685013240, dubbo version: 2.5.3, current host: 192.168.80.58
com.alibaba.dubbo.remoting.RemotingException: client(url: dubbo://192.168.20.2:20880/com.xiniunet.security.service.SecurityService?anyhost=true&application=web_tutorial&check=false&codec=dubbo&dubbo=2.5.3&heartbeat=60000&interface=com.xiniunet.security.service.SecurityService&loadbalance=roundrobin&methods=checkValification,modifyMemberLoginPassword,resetUserLoginPassword,verifyTransactionPassword,createPassport,deleteOauth,getApplicationAllListByTenantId,createUserOauth,getVersion,createLoginPassword,createTenantUserLoginPassword,checkLoginCode,findUserOauth,createVerificationCode,createLoginCode,searchUserHasSetTransactionPassword,login,createValification,findApplicationInstall,issuePassportByAppkey,revokePassport,existInstallByAppKey,getUserByAccountAndMobile,resetUserTransactionPassword,updateResetLoginPassword,loginByOauth,changeMobileNumber,modifyLoginPassword,getAuthList,resetPasswordByMobile,isResetableLoginPassword,updateUserApplication,updateUserTransactionPassword,searchUserApplication,initializedApplication,findVerificationCode,updateLoginPasswordByVerifyCode,getApplicationAllListByUserId,getPassport,createBatchLoginPassword&monitor=dubbo%3A%2F%2F192.168.20.2%3A2181%2Fcom.alibaba.dubbo.registry.RegistryService%3Fapplication%3Dweb_tutorial%26dubbo%3D2.5.3%26file%3Ddubbo-register-192.168.20.2-web_tutorial.properties%26owner%3Dall%26pid%3D12416%26protocol%3Dregistry%26refer%3Ddubbo%253D2.5.3%2526interface%253Dcom.alibaba.dubbo.monitor.MonitorService%2526pid%253D12416%2526timestamp%253D1490685013286%26registry%3Dzookeeper%26timestamp%3D1490685013285&owner=all&payload=353554432&pid=12416&retries=0&revision=4.6.1-20170322.072501-1&side=consumer&timeout=60000&timestamp=1490685013240) failed to connect to server /192.168.20.2:20880, error message is:Connection refused: no further information
	at com.alibaba.dubbo.remoting.transport.netty.NettyClient.doConnect(NettyClient.java:124)
	at com.alibaba.dubbo.remoting.transport.AbstractClient.connect(AbstractClient.java:280)
	at com.alibaba.dubbo.remoting.transport.AbstractClient$1.run(AbstractClient.java:145)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.connect(NioClientSocketPipelineSink.java:496)
	at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.processSelectedKeys(NioClientSocketPipelineSink.java:452)
	at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.run(NioClientSocketPipelineSink.java:365)
	... 3 more
